### ISSUE TITLE
rdflib dependency not installing properly in Bluemix Node-RED app

### ISSUE THREAD

**Issue by jamsden** [OSLC/alert-node#5]
One of the dependencies I use is oslc-client, and it uses a fork I had to create on rdflib.js to address an issue that has not yet been incorporated. To pick this up, I used this dependency:

  "dependencies": {
    "async": "^2.6.0",
    "rdflib": "git://github.com/OSLC/rdflib.js.git",
    "request": "^2.85.0"
  },

This works fine locally, but in the Bluemix runtime for my app, the node_modules/rdflib is missing the rdflib/lib and node_modules folders, so I get an error when my sample Node-RED flow runs saying rdflib can't be found.

**Comment by berezovskyi** [comment]
try https instead of git:// 

the latter might require SSH keys

**Comment by jamsden** [comment]
That didn't work either. Looks like the module needs to come directly from npm.

**Comment by berezovskyi** [comment]
How about the PR you sent to the rdflib folks? I though you found a more elegant solution that makes everyone happy.

–Andrew.

**Comment by jamsden** [comment]
rdflib.js 0.16.9 contains the XMLLiteral fix.
